### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by djtb2924** [JohnnyCrazy/glua-scrapper#6]
I've tried with multiple versions, when the scraper do :

`Processing [319/1393] gamemode: http://wiki.garrysmod.com/page/gamemode/Register`

The page is fetched (I checked with Fiddler) and an exception is shown :
```
System.NullReferenceException: Object reference not set to an instance of an object
    at glua_scraper.Program.LoadLibraries()
    at glua_scraper.Program.Main(String[] args)
```

**Comment by djtb2924** [comment]
Finnaly I made one in Lua
